
package mx.ihsa.integracion.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UsuariosWebserviceService", targetNamespace = "http://webservice.integracion.ihsa.mx/", wsdlLocation = "http://localhost:9999/integracion-soap-jpa/ws/usuariosWebService?wsdl")
public class UsuariosWebserviceService
    extends Service
{

    private final static URL USUARIOSWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException USUARIOSWEBSERVICESERVICE_EXCEPTION;
    private final static QName USUARIOSWEBSERVICESERVICE_QNAME = new QName("http://webservice.integracion.ihsa.mx/", "UsuariosWebserviceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/integracion-soap-jpa/ws/usuariosWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USUARIOSWEBSERVICESERVICE_WSDL_LOCATION = url;
        USUARIOSWEBSERVICESERVICE_EXCEPTION = e;
    }

    public UsuariosWebserviceService() {
        super(__getWsdlLocation(), USUARIOSWEBSERVICESERVICE_QNAME);
    }

    public UsuariosWebserviceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USUARIOSWEBSERVICESERVICE_QNAME, features);
    }

    public UsuariosWebserviceService(URL wsdlLocation) {
        super(wsdlLocation, USUARIOSWEBSERVICESERVICE_QNAME);
    }

    public UsuariosWebserviceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USUARIOSWEBSERVICESERVICE_QNAME, features);
    }

    public UsuariosWebserviceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UsuariosWebserviceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UsuariosWebservice
     */
    @WebEndpoint(name = "UsuariosWebservicePort")
    public UsuariosWebservice getUsuariosWebservicePort() {
        return super.getPort(new QName("http://webservice.integracion.ihsa.mx/", "UsuariosWebservicePort"), UsuariosWebservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UsuariosWebservice
     */
    @WebEndpoint(name = "UsuariosWebservicePort")
    public UsuariosWebservice getUsuariosWebservicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.integracion.ihsa.mx/", "UsuariosWebservicePort"), UsuariosWebservice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USUARIOSWEBSERVICESERVICE_EXCEPTION!= null) {
            throw USUARIOSWEBSERVICESERVICE_EXCEPTION;
        }
        return USUARIOSWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
