
package mx.ihsa.soap.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PerfilWebserviceService", targetNamespace = "http://webservice.soap.ihsa.mx/", wsdlLocation = "http://localhost:8080/spring-soap/ws/perfiles?wsdl")
public class PerfilWebserviceService
    extends Service
{

    private final static URL PERFILWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PERFILWEBSERVICESERVICE_EXCEPTION;
    private final static QName PERFILWEBSERVICESERVICE_QNAME = new QName("http://webservice.soap.ihsa.mx/", "PerfilWebserviceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/spring-soap/ws/perfiles?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERFILWEBSERVICESERVICE_WSDL_LOCATION = url;
        PERFILWEBSERVICESERVICE_EXCEPTION = e;
    }

    public PerfilWebserviceService() {
        super(__getWsdlLocation(), PERFILWEBSERVICESERVICE_QNAME);
    }

    public PerfilWebserviceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERFILWEBSERVICESERVICE_QNAME, features);
    }

    public PerfilWebserviceService(URL wsdlLocation) {
        super(wsdlLocation, PERFILWEBSERVICESERVICE_QNAME);
    }

    public PerfilWebserviceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERFILWEBSERVICESERVICE_QNAME, features);
    }

    public PerfilWebserviceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PerfilWebserviceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PerfilWebservice
     */
    @WebEndpoint(name = "PerfilWebservicePort")
    public PerfilWebservice getPerfilWebservicePort() {
        return super.getPort(new QName("http://webservice.soap.ihsa.mx/", "PerfilWebservicePort"), PerfilWebservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PerfilWebservice
     */
    @WebEndpoint(name = "PerfilWebservicePort")
    public PerfilWebservice getPerfilWebservicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.soap.ihsa.mx/", "PerfilWebservicePort"), PerfilWebservice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERFILWEBSERVICESERVICE_EXCEPTION!= null) {
            throw PERFILWEBSERVICESERVICE_EXCEPTION;
        }
        return PERFILWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
