
package mx.ihsa.soap.webservice;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioWeb", targetNamespace = "http://webservice.soap.ihsa.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioWeb {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saludar", targetNamespace = "http://webservice.soap.ihsa.mx/", className = "mx.ihsa.soap.webservice.Saludar")
    @ResponseWrapper(localName = "saludarResponse", targetNamespace = "http://webservice.soap.ihsa.mx/", className = "mx.ihsa.soap.webservice.SaludarResponse")
    @Action(input = "http://webservice.soap.ihsa.mx/ServicioWeb/saludarRequest", output = "http://webservice.soap.ihsa.mx/ServicioWeb/saludarResponse")
    public String saludar();

}
