package mx.ihsa.mybatis.model;

public class Cliente {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cliente.id_cte
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    private Integer idCte;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cliente.nom_cte
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    private String nomCte;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cliente.ape_pat_cte
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    private String apePatCte;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cliente.ape_mat_cte
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    private String apeMatCte;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cliente.tel_cte
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    private String telCte;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cliente.dir_cte
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    private String dirCte;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cliente.id_edo_cte
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    private Integer idEdoCte;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cliente.id_cte
     *
     * @return the value of public.cliente.id_cte
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public Integer getIdCte() {
        return idCte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cliente.id_cte
     *
     * @param idCte the value for public.cliente.id_cte
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setIdCte(Integer idCte) {
        this.idCte = idCte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cliente.nom_cte
     *
     * @return the value of public.cliente.nom_cte
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public String getNomCte() {
        return nomCte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cliente.nom_cte
     *
     * @param nomCte the value for public.cliente.nom_cte
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setNomCte(String nomCte) {
        this.nomCte = nomCte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cliente.ape_pat_cte
     *
     * @return the value of public.cliente.ape_pat_cte
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public String getApePatCte() {
        return apePatCte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cliente.ape_pat_cte
     *
     * @param apePatCte the value for public.cliente.ape_pat_cte
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setApePatCte(String apePatCte) {
        this.apePatCte = apePatCte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cliente.ape_mat_cte
     *
     * @return the value of public.cliente.ape_mat_cte
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public String getApeMatCte() {
        return apeMatCte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cliente.ape_mat_cte
     *
     * @param apeMatCte the value for public.cliente.ape_mat_cte
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setApeMatCte(String apeMatCte) {
        this.apeMatCte = apeMatCte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cliente.tel_cte
     *
     * @return the value of public.cliente.tel_cte
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public String getTelCte() {
        return telCte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cliente.tel_cte
     *
     * @param telCte the value for public.cliente.tel_cte
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setTelCte(String telCte) {
        this.telCte = telCte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cliente.dir_cte
     *
     * @return the value of public.cliente.dir_cte
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public String getDirCte() {
        return dirCte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cliente.dir_cte
     *
     * @param dirCte the value for public.cliente.dir_cte
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setDirCte(String dirCte) {
        this.dirCte = dirCte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cliente.id_edo_cte
     *
     * @return the value of public.cliente.id_edo_cte
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public Integer getIdEdoCte() {
        return idEdoCte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cliente.id_edo_cte
     *
     * @param idEdoCte the value for public.cliente.id_edo_cte
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setIdEdoCte(Integer idEdoCte) {
        this.idEdoCte = idEdoCte;
    }
}