package mx.ihsa.mybatis.model;

import java.util.Date;

public class Cuenta {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cuenta.id_cta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    private Integer idCta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cuenta.no_cta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    private String noCta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cuenta.fch_alt
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    private Date fchAlt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cuenta.fch_cre
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    private Date fchCre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cuenta.fch_mod
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    private Date fchMod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cuenta.no_tar
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    private String noTar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cuenta.id_cte
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    private Integer idCte;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cuenta.id_cta
     *
     * @return the value of public.cuenta.id_cta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public Integer getIdCta() {
        return idCta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cuenta.id_cta
     *
     * @param idCta the value for public.cuenta.id_cta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setIdCta(Integer idCta) {
        this.idCta = idCta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cuenta.no_cta
     *
     * @return the value of public.cuenta.no_cta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public String getNoCta() {
        return noCta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cuenta.no_cta
     *
     * @param noCta the value for public.cuenta.no_cta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setNoCta(String noCta) {
        this.noCta = noCta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cuenta.fch_alt
     *
     * @return the value of public.cuenta.fch_alt
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public Date getFchAlt() {
        return fchAlt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cuenta.fch_alt
     *
     * @param fchAlt the value for public.cuenta.fch_alt
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setFchAlt(Date fchAlt) {
        this.fchAlt = fchAlt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cuenta.fch_cre
     *
     * @return the value of public.cuenta.fch_cre
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public Date getFchCre() {
        return fchCre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cuenta.fch_cre
     *
     * @param fchCre the value for public.cuenta.fch_cre
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setFchCre(Date fchCre) {
        this.fchCre = fchCre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cuenta.fch_mod
     *
     * @return the value of public.cuenta.fch_mod
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public Date getFchMod() {
        return fchMod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cuenta.fch_mod
     *
     * @param fchMod the value for public.cuenta.fch_mod
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setFchMod(Date fchMod) {
        this.fchMod = fchMod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cuenta.no_tar
     *
     * @return the value of public.cuenta.no_tar
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public String getNoTar() {
        return noTar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cuenta.no_tar
     *
     * @param noTar the value for public.cuenta.no_tar
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setNoTar(String noTar) {
        this.noTar = noTar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cuenta.id_cte
     *
     * @return the value of public.cuenta.id_cte
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public Integer getIdCte() {
        return idCte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cuenta.id_cte
     *
     * @param idCte the value for public.cuenta.id_cte
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setIdCte(Integer idCte) {
        this.idCte = idCte;
    }
}