package mx.ihsa.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CuentaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.cuenta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.cuenta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.cuenta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cuenta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public CuentaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cuenta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cuenta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cuenta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cuenta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cuenta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cuenta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cuenta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cuenta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cuenta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cuenta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.cuenta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdCtaIsNull() {
            addCriterion("id_cta is null");
            return (Criteria) this;
        }

        public Criteria andIdCtaIsNotNull() {
            addCriterion("id_cta is not null");
            return (Criteria) this;
        }

        public Criteria andIdCtaEqualTo(Integer value) {
            addCriterion("id_cta =", value, "idCta");
            return (Criteria) this;
        }

        public Criteria andIdCtaNotEqualTo(Integer value) {
            addCriterion("id_cta <>", value, "idCta");
            return (Criteria) this;
        }

        public Criteria andIdCtaGreaterThan(Integer value) {
            addCriterion("id_cta >", value, "idCta");
            return (Criteria) this;
        }

        public Criteria andIdCtaGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_cta >=", value, "idCta");
            return (Criteria) this;
        }

        public Criteria andIdCtaLessThan(Integer value) {
            addCriterion("id_cta <", value, "idCta");
            return (Criteria) this;
        }

        public Criteria andIdCtaLessThanOrEqualTo(Integer value) {
            addCriterion("id_cta <=", value, "idCta");
            return (Criteria) this;
        }

        public Criteria andIdCtaIn(List<Integer> values) {
            addCriterion("id_cta in", values, "idCta");
            return (Criteria) this;
        }

        public Criteria andIdCtaNotIn(List<Integer> values) {
            addCriterion("id_cta not in", values, "idCta");
            return (Criteria) this;
        }

        public Criteria andIdCtaBetween(Integer value1, Integer value2) {
            addCriterion("id_cta between", value1, value2, "idCta");
            return (Criteria) this;
        }

        public Criteria andIdCtaNotBetween(Integer value1, Integer value2) {
            addCriterion("id_cta not between", value1, value2, "idCta");
            return (Criteria) this;
        }

        public Criteria andNoCtaIsNull() {
            addCriterion("no_cta is null");
            return (Criteria) this;
        }

        public Criteria andNoCtaIsNotNull() {
            addCriterion("no_cta is not null");
            return (Criteria) this;
        }

        public Criteria andNoCtaEqualTo(String value) {
            addCriterion("no_cta =", value, "noCta");
            return (Criteria) this;
        }

        public Criteria andNoCtaNotEqualTo(String value) {
            addCriterion("no_cta <>", value, "noCta");
            return (Criteria) this;
        }

        public Criteria andNoCtaGreaterThan(String value) {
            addCriterion("no_cta >", value, "noCta");
            return (Criteria) this;
        }

        public Criteria andNoCtaGreaterThanOrEqualTo(String value) {
            addCriterion("no_cta >=", value, "noCta");
            return (Criteria) this;
        }

        public Criteria andNoCtaLessThan(String value) {
            addCriterion("no_cta <", value, "noCta");
            return (Criteria) this;
        }

        public Criteria andNoCtaLessThanOrEqualTo(String value) {
            addCriterion("no_cta <=", value, "noCta");
            return (Criteria) this;
        }

        public Criteria andNoCtaLike(String value) {
            addCriterion("no_cta like", value, "noCta");
            return (Criteria) this;
        }

        public Criteria andNoCtaNotLike(String value) {
            addCriterion("no_cta not like", value, "noCta");
            return (Criteria) this;
        }

        public Criteria andNoCtaIn(List<String> values) {
            addCriterion("no_cta in", values, "noCta");
            return (Criteria) this;
        }

        public Criteria andNoCtaNotIn(List<String> values) {
            addCriterion("no_cta not in", values, "noCta");
            return (Criteria) this;
        }

        public Criteria andNoCtaBetween(String value1, String value2) {
            addCriterion("no_cta between", value1, value2, "noCta");
            return (Criteria) this;
        }

        public Criteria andNoCtaNotBetween(String value1, String value2) {
            addCriterion("no_cta not between", value1, value2, "noCta");
            return (Criteria) this;
        }

        public Criteria andFchAltIsNull() {
            addCriterion("fch_alt is null");
            return (Criteria) this;
        }

        public Criteria andFchAltIsNotNull() {
            addCriterion("fch_alt is not null");
            return (Criteria) this;
        }

        public Criteria andFchAltEqualTo(Date value) {
            addCriterion("fch_alt =", value, "fchAlt");
            return (Criteria) this;
        }

        public Criteria andFchAltNotEqualTo(Date value) {
            addCriterion("fch_alt <>", value, "fchAlt");
            return (Criteria) this;
        }

        public Criteria andFchAltGreaterThan(Date value) {
            addCriterion("fch_alt >", value, "fchAlt");
            return (Criteria) this;
        }

        public Criteria andFchAltGreaterThanOrEqualTo(Date value) {
            addCriterion("fch_alt >=", value, "fchAlt");
            return (Criteria) this;
        }

        public Criteria andFchAltLessThan(Date value) {
            addCriterion("fch_alt <", value, "fchAlt");
            return (Criteria) this;
        }

        public Criteria andFchAltLessThanOrEqualTo(Date value) {
            addCriterion("fch_alt <=", value, "fchAlt");
            return (Criteria) this;
        }

        public Criteria andFchAltIn(List<Date> values) {
            addCriterion("fch_alt in", values, "fchAlt");
            return (Criteria) this;
        }

        public Criteria andFchAltNotIn(List<Date> values) {
            addCriterion("fch_alt not in", values, "fchAlt");
            return (Criteria) this;
        }

        public Criteria andFchAltBetween(Date value1, Date value2) {
            addCriterion("fch_alt between", value1, value2, "fchAlt");
            return (Criteria) this;
        }

        public Criteria andFchAltNotBetween(Date value1, Date value2) {
            addCriterion("fch_alt not between", value1, value2, "fchAlt");
            return (Criteria) this;
        }

        public Criteria andFchCreIsNull() {
            addCriterion("fch_cre is null");
            return (Criteria) this;
        }

        public Criteria andFchCreIsNotNull() {
            addCriterion("fch_cre is not null");
            return (Criteria) this;
        }

        public Criteria andFchCreEqualTo(Date value) {
            addCriterion("fch_cre =", value, "fchCre");
            return (Criteria) this;
        }

        public Criteria andFchCreNotEqualTo(Date value) {
            addCriterion("fch_cre <>", value, "fchCre");
            return (Criteria) this;
        }

        public Criteria andFchCreGreaterThan(Date value) {
            addCriterion("fch_cre >", value, "fchCre");
            return (Criteria) this;
        }

        public Criteria andFchCreGreaterThanOrEqualTo(Date value) {
            addCriterion("fch_cre >=", value, "fchCre");
            return (Criteria) this;
        }

        public Criteria andFchCreLessThan(Date value) {
            addCriterion("fch_cre <", value, "fchCre");
            return (Criteria) this;
        }

        public Criteria andFchCreLessThanOrEqualTo(Date value) {
            addCriterion("fch_cre <=", value, "fchCre");
            return (Criteria) this;
        }

        public Criteria andFchCreIn(List<Date> values) {
            addCriterion("fch_cre in", values, "fchCre");
            return (Criteria) this;
        }

        public Criteria andFchCreNotIn(List<Date> values) {
            addCriterion("fch_cre not in", values, "fchCre");
            return (Criteria) this;
        }

        public Criteria andFchCreBetween(Date value1, Date value2) {
            addCriterion("fch_cre between", value1, value2, "fchCre");
            return (Criteria) this;
        }

        public Criteria andFchCreNotBetween(Date value1, Date value2) {
            addCriterion("fch_cre not between", value1, value2, "fchCre");
            return (Criteria) this;
        }

        public Criteria andFchModIsNull() {
            addCriterion("fch_mod is null");
            return (Criteria) this;
        }

        public Criteria andFchModIsNotNull() {
            addCriterion("fch_mod is not null");
            return (Criteria) this;
        }

        public Criteria andFchModEqualTo(Date value) {
            addCriterion("fch_mod =", value, "fchMod");
            return (Criteria) this;
        }

        public Criteria andFchModNotEqualTo(Date value) {
            addCriterion("fch_mod <>", value, "fchMod");
            return (Criteria) this;
        }

        public Criteria andFchModGreaterThan(Date value) {
            addCriterion("fch_mod >", value, "fchMod");
            return (Criteria) this;
        }

        public Criteria andFchModGreaterThanOrEqualTo(Date value) {
            addCriterion("fch_mod >=", value, "fchMod");
            return (Criteria) this;
        }

        public Criteria andFchModLessThan(Date value) {
            addCriterion("fch_mod <", value, "fchMod");
            return (Criteria) this;
        }

        public Criteria andFchModLessThanOrEqualTo(Date value) {
            addCriterion("fch_mod <=", value, "fchMod");
            return (Criteria) this;
        }

        public Criteria andFchModIn(List<Date> values) {
            addCriterion("fch_mod in", values, "fchMod");
            return (Criteria) this;
        }

        public Criteria andFchModNotIn(List<Date> values) {
            addCriterion("fch_mod not in", values, "fchMod");
            return (Criteria) this;
        }

        public Criteria andFchModBetween(Date value1, Date value2) {
            addCriterion("fch_mod between", value1, value2, "fchMod");
            return (Criteria) this;
        }

        public Criteria andFchModNotBetween(Date value1, Date value2) {
            addCriterion("fch_mod not between", value1, value2, "fchMod");
            return (Criteria) this;
        }

        public Criteria andNoTarIsNull() {
            addCriterion("no_tar is null");
            return (Criteria) this;
        }

        public Criteria andNoTarIsNotNull() {
            addCriterion("no_tar is not null");
            return (Criteria) this;
        }

        public Criteria andNoTarEqualTo(String value) {
            addCriterion("no_tar =", value, "noTar");
            return (Criteria) this;
        }

        public Criteria andNoTarNotEqualTo(String value) {
            addCriterion("no_tar <>", value, "noTar");
            return (Criteria) this;
        }

        public Criteria andNoTarGreaterThan(String value) {
            addCriterion("no_tar >", value, "noTar");
            return (Criteria) this;
        }

        public Criteria andNoTarGreaterThanOrEqualTo(String value) {
            addCriterion("no_tar >=", value, "noTar");
            return (Criteria) this;
        }

        public Criteria andNoTarLessThan(String value) {
            addCriterion("no_tar <", value, "noTar");
            return (Criteria) this;
        }

        public Criteria andNoTarLessThanOrEqualTo(String value) {
            addCriterion("no_tar <=", value, "noTar");
            return (Criteria) this;
        }

        public Criteria andNoTarLike(String value) {
            addCriterion("no_tar like", value, "noTar");
            return (Criteria) this;
        }

        public Criteria andNoTarNotLike(String value) {
            addCriterion("no_tar not like", value, "noTar");
            return (Criteria) this;
        }

        public Criteria andNoTarIn(List<String> values) {
            addCriterion("no_tar in", values, "noTar");
            return (Criteria) this;
        }

        public Criteria andNoTarNotIn(List<String> values) {
            addCriterion("no_tar not in", values, "noTar");
            return (Criteria) this;
        }

        public Criteria andNoTarBetween(String value1, String value2) {
            addCriterion("no_tar between", value1, value2, "noTar");
            return (Criteria) this;
        }

        public Criteria andNoTarNotBetween(String value1, String value2) {
            addCriterion("no_tar not between", value1, value2, "noTar");
            return (Criteria) this;
        }

        public Criteria andIdCteIsNull() {
            addCriterion("id_cte is null");
            return (Criteria) this;
        }

        public Criteria andIdCteIsNotNull() {
            addCriterion("id_cte is not null");
            return (Criteria) this;
        }

        public Criteria andIdCteEqualTo(Integer value) {
            addCriterion("id_cte =", value, "idCte");
            return (Criteria) this;
        }

        public Criteria andIdCteNotEqualTo(Integer value) {
            addCriterion("id_cte <>", value, "idCte");
            return (Criteria) this;
        }

        public Criteria andIdCteGreaterThan(Integer value) {
            addCriterion("id_cte >", value, "idCte");
            return (Criteria) this;
        }

        public Criteria andIdCteGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_cte >=", value, "idCte");
            return (Criteria) this;
        }

        public Criteria andIdCteLessThan(Integer value) {
            addCriterion("id_cte <", value, "idCte");
            return (Criteria) this;
        }

        public Criteria andIdCteLessThanOrEqualTo(Integer value) {
            addCriterion("id_cte <=", value, "idCte");
            return (Criteria) this;
        }

        public Criteria andIdCteIn(List<Integer> values) {
            addCriterion("id_cte in", values, "idCte");
            return (Criteria) this;
        }

        public Criteria andIdCteNotIn(List<Integer> values) {
            addCriterion("id_cte not in", values, "idCte");
            return (Criteria) this;
        }

        public Criteria andIdCteBetween(Integer value1, Integer value2) {
            addCriterion("id_cte between", value1, value2, "idCte");
            return (Criteria) this;
        }

        public Criteria andIdCteNotBetween(Integer value1, Integer value2) {
            addCriterion("id_cte not between", value1, value2, "idCte");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.cuenta
     *
     * @mbg.generated do_not_delete_during_merge Fri Feb 22 12:24:36 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.cuenta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}