package mx.ihsa.mybatis.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MovimientoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.movimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.movimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.movimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public MovimientoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.movimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdMovCtaIsNull() {
            addCriterion("id_mov_cta is null");
            return (Criteria) this;
        }

        public Criteria andIdMovCtaIsNotNull() {
            addCriterion("id_mov_cta is not null");
            return (Criteria) this;
        }

        public Criteria andIdMovCtaEqualTo(Integer value) {
            addCriterion("id_mov_cta =", value, "idMovCta");
            return (Criteria) this;
        }

        public Criteria andIdMovCtaNotEqualTo(Integer value) {
            addCriterion("id_mov_cta <>", value, "idMovCta");
            return (Criteria) this;
        }

        public Criteria andIdMovCtaGreaterThan(Integer value) {
            addCriterion("id_mov_cta >", value, "idMovCta");
            return (Criteria) this;
        }

        public Criteria andIdMovCtaGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_mov_cta >=", value, "idMovCta");
            return (Criteria) this;
        }

        public Criteria andIdMovCtaLessThan(Integer value) {
            addCriterion("id_mov_cta <", value, "idMovCta");
            return (Criteria) this;
        }

        public Criteria andIdMovCtaLessThanOrEqualTo(Integer value) {
            addCriterion("id_mov_cta <=", value, "idMovCta");
            return (Criteria) this;
        }

        public Criteria andIdMovCtaIn(List<Integer> values) {
            addCriterion("id_mov_cta in", values, "idMovCta");
            return (Criteria) this;
        }

        public Criteria andIdMovCtaNotIn(List<Integer> values) {
            addCriterion("id_mov_cta not in", values, "idMovCta");
            return (Criteria) this;
        }

        public Criteria andIdMovCtaBetween(Integer value1, Integer value2) {
            addCriterion("id_mov_cta between", value1, value2, "idMovCta");
            return (Criteria) this;
        }

        public Criteria andIdMovCtaNotBetween(Integer value1, Integer value2) {
            addCriterion("id_mov_cta not between", value1, value2, "idMovCta");
            return (Criteria) this;
        }

        public Criteria andIdCtaIsNull() {
            addCriterion("id_cta is null");
            return (Criteria) this;
        }

        public Criteria andIdCtaIsNotNull() {
            addCriterion("id_cta is not null");
            return (Criteria) this;
        }

        public Criteria andIdCtaEqualTo(Integer value) {
            addCriterion("id_cta =", value, "idCta");
            return (Criteria) this;
        }

        public Criteria andIdCtaNotEqualTo(Integer value) {
            addCriterion("id_cta <>", value, "idCta");
            return (Criteria) this;
        }

        public Criteria andIdCtaGreaterThan(Integer value) {
            addCriterion("id_cta >", value, "idCta");
            return (Criteria) this;
        }

        public Criteria andIdCtaGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_cta >=", value, "idCta");
            return (Criteria) this;
        }

        public Criteria andIdCtaLessThan(Integer value) {
            addCriterion("id_cta <", value, "idCta");
            return (Criteria) this;
        }

        public Criteria andIdCtaLessThanOrEqualTo(Integer value) {
            addCriterion("id_cta <=", value, "idCta");
            return (Criteria) this;
        }

        public Criteria andIdCtaIn(List<Integer> values) {
            addCriterion("id_cta in", values, "idCta");
            return (Criteria) this;
        }

        public Criteria andIdCtaNotIn(List<Integer> values) {
            addCriterion("id_cta not in", values, "idCta");
            return (Criteria) this;
        }

        public Criteria andIdCtaBetween(Integer value1, Integer value2) {
            addCriterion("id_cta between", value1, value2, "idCta");
            return (Criteria) this;
        }

        public Criteria andIdCtaNotBetween(Integer value1, Integer value2) {
            addCriterion("id_cta not between", value1, value2, "idCta");
            return (Criteria) this;
        }

        public Criteria andFchCreIsNull() {
            addCriterion("fch_cre is null");
            return (Criteria) this;
        }

        public Criteria andFchCreIsNotNull() {
            addCriterion("fch_cre is not null");
            return (Criteria) this;
        }

        public Criteria andFchCreEqualTo(Date value) {
            addCriterion("fch_cre =", value, "fchCre");
            return (Criteria) this;
        }

        public Criteria andFchCreNotEqualTo(Date value) {
            addCriterion("fch_cre <>", value, "fchCre");
            return (Criteria) this;
        }

        public Criteria andFchCreGreaterThan(Date value) {
            addCriterion("fch_cre >", value, "fchCre");
            return (Criteria) this;
        }

        public Criteria andFchCreGreaterThanOrEqualTo(Date value) {
            addCriterion("fch_cre >=", value, "fchCre");
            return (Criteria) this;
        }

        public Criteria andFchCreLessThan(Date value) {
            addCriterion("fch_cre <", value, "fchCre");
            return (Criteria) this;
        }

        public Criteria andFchCreLessThanOrEqualTo(Date value) {
            addCriterion("fch_cre <=", value, "fchCre");
            return (Criteria) this;
        }

        public Criteria andFchCreIn(List<Date> values) {
            addCriterion("fch_cre in", values, "fchCre");
            return (Criteria) this;
        }

        public Criteria andFchCreNotIn(List<Date> values) {
            addCriterion("fch_cre not in", values, "fchCre");
            return (Criteria) this;
        }

        public Criteria andFchCreBetween(Date value1, Date value2) {
            addCriterion("fch_cre between", value1, value2, "fchCre");
            return (Criteria) this;
        }

        public Criteria andFchCreNotBetween(Date value1, Date value2) {
            addCriterion("fch_cre not between", value1, value2, "fchCre");
            return (Criteria) this;
        }

        public Criteria andIdTipMovIsNull() {
            addCriterion("id_tip_mov is null");
            return (Criteria) this;
        }

        public Criteria andIdTipMovIsNotNull() {
            addCriterion("id_tip_mov is not null");
            return (Criteria) this;
        }

        public Criteria andIdTipMovEqualTo(Integer value) {
            addCriterion("id_tip_mov =", value, "idTipMov");
            return (Criteria) this;
        }

        public Criteria andIdTipMovNotEqualTo(Integer value) {
            addCriterion("id_tip_mov <>", value, "idTipMov");
            return (Criteria) this;
        }

        public Criteria andIdTipMovGreaterThan(Integer value) {
            addCriterion("id_tip_mov >", value, "idTipMov");
            return (Criteria) this;
        }

        public Criteria andIdTipMovGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_tip_mov >=", value, "idTipMov");
            return (Criteria) this;
        }

        public Criteria andIdTipMovLessThan(Integer value) {
            addCriterion("id_tip_mov <", value, "idTipMov");
            return (Criteria) this;
        }

        public Criteria andIdTipMovLessThanOrEqualTo(Integer value) {
            addCriterion("id_tip_mov <=", value, "idTipMov");
            return (Criteria) this;
        }

        public Criteria andIdTipMovIn(List<Integer> values) {
            addCriterion("id_tip_mov in", values, "idTipMov");
            return (Criteria) this;
        }

        public Criteria andIdTipMovNotIn(List<Integer> values) {
            addCriterion("id_tip_mov not in", values, "idTipMov");
            return (Criteria) this;
        }

        public Criteria andIdTipMovBetween(Integer value1, Integer value2) {
            addCriterion("id_tip_mov between", value1, value2, "idTipMov");
            return (Criteria) this;
        }

        public Criteria andIdTipMovNotBetween(Integer value1, Integer value2) {
            addCriterion("id_tip_mov not between", value1, value2, "idTipMov");
            return (Criteria) this;
        }

        public Criteria andMntMovIsNull() {
            addCriterion("mnt_mov is null");
            return (Criteria) this;
        }

        public Criteria andMntMovIsNotNull() {
            addCriterion("mnt_mov is not null");
            return (Criteria) this;
        }

        public Criteria andMntMovEqualTo(BigDecimal value) {
            addCriterion("mnt_mov =", value, "mntMov");
            return (Criteria) this;
        }

        public Criteria andMntMovNotEqualTo(BigDecimal value) {
            addCriterion("mnt_mov <>", value, "mntMov");
            return (Criteria) this;
        }

        public Criteria andMntMovGreaterThan(BigDecimal value) {
            addCriterion("mnt_mov >", value, "mntMov");
            return (Criteria) this;
        }

        public Criteria andMntMovGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mnt_mov >=", value, "mntMov");
            return (Criteria) this;
        }

        public Criteria andMntMovLessThan(BigDecimal value) {
            addCriterion("mnt_mov <", value, "mntMov");
            return (Criteria) this;
        }

        public Criteria andMntMovLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mnt_mov <=", value, "mntMov");
            return (Criteria) this;
        }

        public Criteria andMntMovIn(List<BigDecimal> values) {
            addCriterion("mnt_mov in", values, "mntMov");
            return (Criteria) this;
        }

        public Criteria andMntMovNotIn(List<BigDecimal> values) {
            addCriterion("mnt_mov not in", values, "mntMov");
            return (Criteria) this;
        }

        public Criteria andMntMovBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mnt_mov between", value1, value2, "mntMov");
            return (Criteria) this;
        }

        public Criteria andMntMovNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mnt_mov not between", value1, value2, "mntMov");
            return (Criteria) this;
        }

        public Criteria andDscMovIsNull() {
            addCriterion("dsc_mov is null");
            return (Criteria) this;
        }

        public Criteria andDscMovIsNotNull() {
            addCriterion("dsc_mov is not null");
            return (Criteria) this;
        }

        public Criteria andDscMovEqualTo(String value) {
            addCriterion("dsc_mov =", value, "dscMov");
            return (Criteria) this;
        }

        public Criteria andDscMovNotEqualTo(String value) {
            addCriterion("dsc_mov <>", value, "dscMov");
            return (Criteria) this;
        }

        public Criteria andDscMovGreaterThan(String value) {
            addCriterion("dsc_mov >", value, "dscMov");
            return (Criteria) this;
        }

        public Criteria andDscMovGreaterThanOrEqualTo(String value) {
            addCriterion("dsc_mov >=", value, "dscMov");
            return (Criteria) this;
        }

        public Criteria andDscMovLessThan(String value) {
            addCriterion("dsc_mov <", value, "dscMov");
            return (Criteria) this;
        }

        public Criteria andDscMovLessThanOrEqualTo(String value) {
            addCriterion("dsc_mov <=", value, "dscMov");
            return (Criteria) this;
        }

        public Criteria andDscMovLike(String value) {
            addCriterion("dsc_mov like", value, "dscMov");
            return (Criteria) this;
        }

        public Criteria andDscMovNotLike(String value) {
            addCriterion("dsc_mov not like", value, "dscMov");
            return (Criteria) this;
        }

        public Criteria andDscMovIn(List<String> values) {
            addCriterion("dsc_mov in", values, "dscMov");
            return (Criteria) this;
        }

        public Criteria andDscMovNotIn(List<String> values) {
            addCriterion("dsc_mov not in", values, "dscMov");
            return (Criteria) this;
        }

        public Criteria andDscMovBetween(String value1, String value2) {
            addCriterion("dsc_mov between", value1, value2, "dscMov");
            return (Criteria) this;
        }

        public Criteria andDscMovNotBetween(String value1, String value2) {
            addCriterion("dsc_mov not between", value1, value2, "dscMov");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.movimiento
     *
     * @mbg.generated do_not_delete_during_merge Fri Feb 22 12:24:36 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.movimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}