package mx.ihsa.mybatis.model;

public class Perfil {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.perfil.id_perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    private Integer idPerfil;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.perfil.desc_perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    private String descPerfil;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.perfil.observaciones
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    private String observaciones;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.perfil.id_perfil
     *
     * @return the value of public.perfil.id_perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public Integer getIdPerfil() {
        return idPerfil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.perfil.id_perfil
     *
     * @param idPerfil the value for public.perfil.id_perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setIdPerfil(Integer idPerfil) {
        this.idPerfil = idPerfil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.perfil.desc_perfil
     *
     * @return the value of public.perfil.desc_perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public String getDescPerfil() {
        return descPerfil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.perfil.desc_perfil
     *
     * @param descPerfil the value for public.perfil.desc_perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setDescPerfil(String descPerfil) {
        this.descPerfil = descPerfil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.perfil.observaciones
     *
     * @return the value of public.perfil.observaciones
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public String getObservaciones() {
        return observaciones;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.perfil.observaciones
     *
     * @param observaciones the value for public.perfil.observaciones
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
}