package mx.ihsa.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class PerfilExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public PerfilExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdPerfilIsNull() {
            addCriterion("id_perfil is null");
            return (Criteria) this;
        }

        public Criteria andIdPerfilIsNotNull() {
            addCriterion("id_perfil is not null");
            return (Criteria) this;
        }

        public Criteria andIdPerfilEqualTo(Integer value) {
            addCriterion("id_perfil =", value, "idPerfil");
            return (Criteria) this;
        }

        public Criteria andIdPerfilNotEqualTo(Integer value) {
            addCriterion("id_perfil <>", value, "idPerfil");
            return (Criteria) this;
        }

        public Criteria andIdPerfilGreaterThan(Integer value) {
            addCriterion("id_perfil >", value, "idPerfil");
            return (Criteria) this;
        }

        public Criteria andIdPerfilGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_perfil >=", value, "idPerfil");
            return (Criteria) this;
        }

        public Criteria andIdPerfilLessThan(Integer value) {
            addCriterion("id_perfil <", value, "idPerfil");
            return (Criteria) this;
        }

        public Criteria andIdPerfilLessThanOrEqualTo(Integer value) {
            addCriterion("id_perfil <=", value, "idPerfil");
            return (Criteria) this;
        }

        public Criteria andIdPerfilIn(List<Integer> values) {
            addCriterion("id_perfil in", values, "idPerfil");
            return (Criteria) this;
        }

        public Criteria andIdPerfilNotIn(List<Integer> values) {
            addCriterion("id_perfil not in", values, "idPerfil");
            return (Criteria) this;
        }

        public Criteria andIdPerfilBetween(Integer value1, Integer value2) {
            addCriterion("id_perfil between", value1, value2, "idPerfil");
            return (Criteria) this;
        }

        public Criteria andIdPerfilNotBetween(Integer value1, Integer value2) {
            addCriterion("id_perfil not between", value1, value2, "idPerfil");
            return (Criteria) this;
        }

        public Criteria andDescPerfilIsNull() {
            addCriterion("desc_perfil is null");
            return (Criteria) this;
        }

        public Criteria andDescPerfilIsNotNull() {
            addCriterion("desc_perfil is not null");
            return (Criteria) this;
        }

        public Criteria andDescPerfilEqualTo(String value) {
            addCriterion("desc_perfil =", value, "descPerfil");
            return (Criteria) this;
        }

        public Criteria andDescPerfilNotEqualTo(String value) {
            addCriterion("desc_perfil <>", value, "descPerfil");
            return (Criteria) this;
        }

        public Criteria andDescPerfilGreaterThan(String value) {
            addCriterion("desc_perfil >", value, "descPerfil");
            return (Criteria) this;
        }

        public Criteria andDescPerfilGreaterThanOrEqualTo(String value) {
            addCriterion("desc_perfil >=", value, "descPerfil");
            return (Criteria) this;
        }

        public Criteria andDescPerfilLessThan(String value) {
            addCriterion("desc_perfil <", value, "descPerfil");
            return (Criteria) this;
        }

        public Criteria andDescPerfilLessThanOrEqualTo(String value) {
            addCriterion("desc_perfil <=", value, "descPerfil");
            return (Criteria) this;
        }

        public Criteria andDescPerfilLike(String value) {
            addCriterion("desc_perfil like", value, "descPerfil");
            return (Criteria) this;
        }

        public Criteria andDescPerfilNotLike(String value) {
            addCriterion("desc_perfil not like", value, "descPerfil");
            return (Criteria) this;
        }

        public Criteria andDescPerfilIn(List<String> values) {
            addCriterion("desc_perfil in", values, "descPerfil");
            return (Criteria) this;
        }

        public Criteria andDescPerfilNotIn(List<String> values) {
            addCriterion("desc_perfil not in", values, "descPerfil");
            return (Criteria) this;
        }

        public Criteria andDescPerfilBetween(String value1, String value2) {
            addCriterion("desc_perfil between", value1, value2, "descPerfil");
            return (Criteria) this;
        }

        public Criteria andDescPerfilNotBetween(String value1, String value2) {
            addCriterion("desc_perfil not between", value1, value2, "descPerfil");
            return (Criteria) this;
        }

        public Criteria andObservacionesIsNull() {
            addCriterion("observaciones is null");
            return (Criteria) this;
        }

        public Criteria andObservacionesIsNotNull() {
            addCriterion("observaciones is not null");
            return (Criteria) this;
        }

        public Criteria andObservacionesEqualTo(String value) {
            addCriterion("observaciones =", value, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesNotEqualTo(String value) {
            addCriterion("observaciones <>", value, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesGreaterThan(String value) {
            addCriterion("observaciones >", value, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesGreaterThanOrEqualTo(String value) {
            addCriterion("observaciones >=", value, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesLessThan(String value) {
            addCriterion("observaciones <", value, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesLessThanOrEqualTo(String value) {
            addCriterion("observaciones <=", value, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesLike(String value) {
            addCriterion("observaciones like", value, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesNotLike(String value) {
            addCriterion("observaciones not like", value, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesIn(List<String> values) {
            addCriterion("observaciones in", values, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesNotIn(List<String> values) {
            addCriterion("observaciones not in", values, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesBetween(String value1, String value2) {
            addCriterion("observaciones between", value1, value2, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesNotBetween(String value1, String value2) {
            addCriterion("observaciones not between", value1, value2, "observaciones");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.perfil
     *
     * @mbg.generated do_not_delete_during_merge Fri Feb 22 12:24:36 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}