package mx.ihsa.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class TipomovimientoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.tipomovimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.tipomovimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.tipomovimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tipomovimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public TipomovimientoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tipomovimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tipomovimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tipomovimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tipomovimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tipomovimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tipomovimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tipomovimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tipomovimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tipomovimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tipomovimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.tipomovimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdTipMovIsNull() {
            addCriterion("id_tip_mov is null");
            return (Criteria) this;
        }

        public Criteria andIdTipMovIsNotNull() {
            addCriterion("id_tip_mov is not null");
            return (Criteria) this;
        }

        public Criteria andIdTipMovEqualTo(Integer value) {
            addCriterion("id_tip_mov =", value, "idTipMov");
            return (Criteria) this;
        }

        public Criteria andIdTipMovNotEqualTo(Integer value) {
            addCriterion("id_tip_mov <>", value, "idTipMov");
            return (Criteria) this;
        }

        public Criteria andIdTipMovGreaterThan(Integer value) {
            addCriterion("id_tip_mov >", value, "idTipMov");
            return (Criteria) this;
        }

        public Criteria andIdTipMovGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_tip_mov >=", value, "idTipMov");
            return (Criteria) this;
        }

        public Criteria andIdTipMovLessThan(Integer value) {
            addCriterion("id_tip_mov <", value, "idTipMov");
            return (Criteria) this;
        }

        public Criteria andIdTipMovLessThanOrEqualTo(Integer value) {
            addCriterion("id_tip_mov <=", value, "idTipMov");
            return (Criteria) this;
        }

        public Criteria andIdTipMovIn(List<Integer> values) {
            addCriterion("id_tip_mov in", values, "idTipMov");
            return (Criteria) this;
        }

        public Criteria andIdTipMovNotIn(List<Integer> values) {
            addCriterion("id_tip_mov not in", values, "idTipMov");
            return (Criteria) this;
        }

        public Criteria andIdTipMovBetween(Integer value1, Integer value2) {
            addCriterion("id_tip_mov between", value1, value2, "idTipMov");
            return (Criteria) this;
        }

        public Criteria andIdTipMovNotBetween(Integer value1, Integer value2) {
            addCriterion("id_tip_mov not between", value1, value2, "idTipMov");
            return (Criteria) this;
        }

        public Criteria andDescTipMovIsNull() {
            addCriterion("desc_tip_mov is null");
            return (Criteria) this;
        }

        public Criteria andDescTipMovIsNotNull() {
            addCriterion("desc_tip_mov is not null");
            return (Criteria) this;
        }

        public Criteria andDescTipMovEqualTo(String value) {
            addCriterion("desc_tip_mov =", value, "descTipMov");
            return (Criteria) this;
        }

        public Criteria andDescTipMovNotEqualTo(String value) {
            addCriterion("desc_tip_mov <>", value, "descTipMov");
            return (Criteria) this;
        }

        public Criteria andDescTipMovGreaterThan(String value) {
            addCriterion("desc_tip_mov >", value, "descTipMov");
            return (Criteria) this;
        }

        public Criteria andDescTipMovGreaterThanOrEqualTo(String value) {
            addCriterion("desc_tip_mov >=", value, "descTipMov");
            return (Criteria) this;
        }

        public Criteria andDescTipMovLessThan(String value) {
            addCriterion("desc_tip_mov <", value, "descTipMov");
            return (Criteria) this;
        }

        public Criteria andDescTipMovLessThanOrEqualTo(String value) {
            addCriterion("desc_tip_mov <=", value, "descTipMov");
            return (Criteria) this;
        }

        public Criteria andDescTipMovLike(String value) {
            addCriterion("desc_tip_mov like", value, "descTipMov");
            return (Criteria) this;
        }

        public Criteria andDescTipMovNotLike(String value) {
            addCriterion("desc_tip_mov not like", value, "descTipMov");
            return (Criteria) this;
        }

        public Criteria andDescTipMovIn(List<String> values) {
            addCriterion("desc_tip_mov in", values, "descTipMov");
            return (Criteria) this;
        }

        public Criteria andDescTipMovNotIn(List<String> values) {
            addCriterion("desc_tip_mov not in", values, "descTipMov");
            return (Criteria) this;
        }

        public Criteria andDescTipMovBetween(String value1, String value2) {
            addCriterion("desc_tip_mov between", value1, value2, "descTipMov");
            return (Criteria) this;
        }

        public Criteria andDescTipMovNotBetween(String value1, String value2) {
            addCriterion("desc_tip_mov not between", value1, value2, "descTipMov");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.tipomovimiento
     *
     * @mbg.generated do_not_delete_during_merge Fri Feb 22 12:24:36 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.tipomovimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}