package mx.ihsa.mybatis.model;

public class Tipomovimiento {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tipomovimiento.id_tip_mov
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    private Integer idTipMov;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tipomovimiento.desc_tip_mov
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    private String descTipMov;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tipomovimiento.id_tip_mov
     *
     * @return the value of public.tipomovimiento.id_tip_mov
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public Integer getIdTipMov() {
        return idTipMov;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tipomovimiento.id_tip_mov
     *
     * @param idTipMov the value for public.tipomovimiento.id_tip_mov
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setIdTipMov(Integer idTipMov) {
        this.idTipMov = idTipMov;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tipomovimiento.desc_tip_mov
     *
     * @return the value of public.tipomovimiento.desc_tip_mov
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public String getDescTipMov() {
        return descTipMov;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tipomovimiento.desc_tip_mov
     *
     * @param descTipMov the value for public.tipomovimiento.desc_tip_mov
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setDescTipMov(String descTipMov) {
        this.descTipMov = descTipMov;
    }
}