package mx.ihsa.mybatis.model;

public class Usuario {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.usuario.id_usuario
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    private Integer idUsuario;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.usuario.username
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.usuario.password
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.usuario.id_perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    private Integer idPerfil;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.usuario.email
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.usuario.activo
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    private Boolean activo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.usuario.imagen
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    private String imagen;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usuario.id_usuario
     *
     * @return the value of public.usuario.id_usuario
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public Integer getIdUsuario() {
        return idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usuario.id_usuario
     *
     * @param idUsuario the value for public.usuario.id_usuario
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usuario.username
     *
     * @return the value of public.usuario.username
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usuario.username
     *
     * @param username the value for public.usuario.username
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usuario.password
     *
     * @return the value of public.usuario.password
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usuario.password
     *
     * @param password the value for public.usuario.password
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usuario.id_perfil
     *
     * @return the value of public.usuario.id_perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public Integer getIdPerfil() {
        return idPerfil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usuario.id_perfil
     *
     * @param idPerfil the value for public.usuario.id_perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setIdPerfil(Integer idPerfil) {
        this.idPerfil = idPerfil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usuario.email
     *
     * @return the value of public.usuario.email
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usuario.email
     *
     * @param email the value for public.usuario.email
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usuario.activo
     *
     * @return the value of public.usuario.activo
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public Boolean getActivo() {
        return activo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usuario.activo
     *
     * @param activo the value for public.usuario.activo
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usuario.imagen
     *
     * @return the value of public.usuario.imagen
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public String getImagen() {
        return imagen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usuario.imagen
     *
     * @param imagen the value for public.usuario.imagen
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
}