package mx.ihsa.integracion.model;
// Generated 19/02/2019 02:52:39 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Movimiento generated by hbm2java
 */
@Entity
@Table(name = "movimiento", schema = "public")
public class Movimiento implements java.io.Serializable {

	private int idMovCta;
	private Cuenta cuenta;
	private Tipomovimiento tipomovimiento;
	private Date fchCre;
	private BigDecimal mntMov;
	private String dscMov;

	public Movimiento() {
	}

	public Movimiento(int idMovCta) {
		this.idMovCta = idMovCta;
	}

	public Movimiento(int idMovCta, Cuenta cuenta, Tipomovimiento tipomovimiento, Date fchCre, BigDecimal mntMov,
			String dscMov) {
		this.idMovCta = idMovCta;
		this.cuenta = cuenta;
		this.tipomovimiento = tipomovimiento;
		this.fchCre = fchCre;
		this.mntMov = mntMov;
		this.dscMov = dscMov;
	}

	@Id

	@Column(name = "id_mov_cta", unique = true, nullable = false)
	public int getIdMovCta() {
		return this.idMovCta;
	}

	public void setIdMovCta(int idMovCta) {
		this.idMovCta = idMovCta;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_cta")
	public Cuenta getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(Cuenta cuenta) {
		this.cuenta = cuenta;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_tip_mov")
	public Tipomovimiento getTipomovimiento() {
		return this.tipomovimiento;
	}

	public void setTipomovimiento(Tipomovimiento tipomovimiento) {
		this.tipomovimiento = tipomovimiento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fch_cre", length = 29)
	public Date getFchCre() {
		return this.fchCre;
	}

	public void setFchCre(Date fchCre) {
		this.fchCre = fchCre;
	}

	@Column(name = "mnt_mov", precision = 20)
	public BigDecimal getMntMov() {
		return this.mntMov;
	}

	public void setMntMov(BigDecimal mntMov) {
		this.mntMov = mntMov;
	}

	@Column(name = "dsc_mov", length = 50)
	public String getDscMov() {
		return this.dscMov;
	}

	public void setDscMov(String dscMov) {
		this.dscMov = dscMov;
	}

}
