package mx.ihsa.integracion.model;
// Generated 19/02/2019 02:52:39 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipomovimiento generated by hbm2java
 */
@Entity
@Table(name = "tipomovimiento", schema = "public")
public class Tipomovimiento implements java.io.Serializable {

	private int idTipMov;
	private String descTipMov;
	

	public Tipomovimiento() {
	}

	public Tipomovimiento(int idTipMov) {
		this.idTipMov = idTipMov;
	}

	@Id

	@Column(name = "id_tip_mov", unique = true, nullable = false)
	public int getIdTipMov() {
		return this.idTipMov;
	}

	public void setIdTipMov(int idTipMov) {
		this.idTipMov = idTipMov;
	}

	@Column(name = "desc_tip_mov", length = 50)
	public String getDescTipMov() {
		return this.descTipMov;
	}

	public void setDescTipMov(String descTipMov) {
		this.descTipMov = descTipMov;
	}

	

}
