package mx.ihsa.integracion.model;
// Generated 19/02/2019 02:52:39 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", schema = "public")
public class Usuario implements java.io.Serializable {

	private int idUsuario;
	private Perfil perfil;
	private String username;
	private String password;
	private boolean activo;
	private String email;

	public Usuario() {
	}

	public Usuario(int idUsuario, Perfil perfil, String username, String password, boolean activo) {
		this.idUsuario = idUsuario;
		this.perfil = perfil;
		this.username = username;
		this.password = password;
		this.activo = activo;
	}

	public Usuario(int idUsuario, Perfil perfil, String username, String password, boolean activo, String email) {
		this.idUsuario = idUsuario;
		this.perfil = perfil;
		this.username = username;
		this.password = password;
		this.activo = activo;
		this.email = email;
	}

	@Id

	@Column(name = "id_usuario", unique = true, nullable = false)
	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_perfil", nullable = false)
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@Column(name = "username", nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 200)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
