
package mx.ihsa.integracion.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TipoMovimientoWebserviceService", targetNamespace = "http://webservice.integracion.ihsa.mx/", wsdlLocation = "http://localhost:9999/integracion-soap-jpa/ws/tipoMovimientoWebService?wsdl")
public class TipoMovimientoWebserviceService
    extends Service
{

    private final static URL TIPOMOVIMIENTOWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException TIPOMOVIMIENTOWEBSERVICESERVICE_EXCEPTION;
    private final static QName TIPOMOVIMIENTOWEBSERVICESERVICE_QNAME = new QName("http://webservice.integracion.ihsa.mx/", "TipoMovimientoWebserviceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/integracion-soap-jpa/ws/tipoMovimientoWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TIPOMOVIMIENTOWEBSERVICESERVICE_WSDL_LOCATION = url;
        TIPOMOVIMIENTOWEBSERVICESERVICE_EXCEPTION = e;
    }

    public TipoMovimientoWebserviceService() {
        super(__getWsdlLocation(), TIPOMOVIMIENTOWEBSERVICESERVICE_QNAME);
    }

    public TipoMovimientoWebserviceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TIPOMOVIMIENTOWEBSERVICESERVICE_QNAME, features);
    }

    public TipoMovimientoWebserviceService(URL wsdlLocation) {
        super(wsdlLocation, TIPOMOVIMIENTOWEBSERVICESERVICE_QNAME);
    }

    public TipoMovimientoWebserviceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TIPOMOVIMIENTOWEBSERVICESERVICE_QNAME, features);
    }

    public TipoMovimientoWebserviceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TipoMovimientoWebserviceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TipoMovimientoWebservice
     */
    @WebEndpoint(name = "TipoMovimientoWebservicePort")
    public TipoMovimientoWebservice getTipoMovimientoWebservicePort() {
        return super.getPort(new QName("http://webservice.integracion.ihsa.mx/", "TipoMovimientoWebservicePort"), TipoMovimientoWebservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TipoMovimientoWebservice
     */
    @WebEndpoint(name = "TipoMovimientoWebservicePort")
    public TipoMovimientoWebservice getTipoMovimientoWebservicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.integracion.ihsa.mx/", "TipoMovimientoWebservicePort"), TipoMovimientoWebservice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TIPOMOVIMIENTOWEBSERVICESERVICE_EXCEPTION!= null) {
            throw TIPOMOVIMIENTOWEBSERVICESERVICE_EXCEPTION;
        }
        return TIPOMOVIMIENTOWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
