
package mx.ihsa.integracion.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TipoMovimientoWebservice", targetNamespace = "http://webservice.integracion.ihsa.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TipoMovimientoWebservice {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "guardar", targetNamespace = "http://webservice.integracion.ihsa.mx/", className = "mx.ihsa.integracion.webservice.Guardar")
    @ResponseWrapper(localName = "guardarResponse", targetNamespace = "http://webservice.integracion.ihsa.mx/", className = "mx.ihsa.integracion.webservice.GuardarResponse")
    @Action(input = "http://webservice.integracion.ihsa.mx/TipoMovimientoWebservice/guardarRequest", output = "http://webservice.integracion.ihsa.mx/TipoMovimientoWebservice/guardarResponse")
    public Integer guardar(
        @WebParam(name = "arg0", targetNamespace = "")
        Tipomovimiento arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eliminar", targetNamespace = "http://webservice.integracion.ihsa.mx/", className = "mx.ihsa.integracion.webservice.Eliminar")
    @ResponseWrapper(localName = "eliminarResponse", targetNamespace = "http://webservice.integracion.ihsa.mx/", className = "mx.ihsa.integracion.webservice.EliminarResponse")
    @Action(input = "http://webservice.integracion.ihsa.mx/TipoMovimientoWebservice/eliminarRequest", output = "http://webservice.integracion.ihsa.mx/TipoMovimientoWebservice/eliminarResponse")
    public boolean eliminar(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @return
     *     returns java.util.List<mx.ihsa.integracion.webservice.Tipomovimiento>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLista", targetNamespace = "http://webservice.integracion.ihsa.mx/", className = "mx.ihsa.integracion.webservice.GetLista")
    @ResponseWrapper(localName = "getListaResponse", targetNamespace = "http://webservice.integracion.ihsa.mx/", className = "mx.ihsa.integracion.webservice.GetListaResponse")
    @Action(input = "http://webservice.integracion.ihsa.mx/TipoMovimientoWebservice/getListaRequest", output = "http://webservice.integracion.ihsa.mx/TipoMovimientoWebservice/getListaResponse")
    public List<Tipomovimiento> getLista();

}
