
package mx.ihsa.integracion.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UsuariosWebservice", targetNamespace = "http://webservice.integracion.ihsa.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UsuariosWebservice {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validarEmail", targetNamespace = "http://webservice.integracion.ihsa.mx/", className = "mx.ihsa.integracion.webservice.ValidarEmail")
    @ResponseWrapper(localName = "validarEmailResponse", targetNamespace = "http://webservice.integracion.ihsa.mx/", className = "mx.ihsa.integracion.webservice.ValidarEmailResponse")
    @Action(input = "http://webservice.integracion.ihsa.mx/UsuariosWebservice/validarEmailRequest", output = "http://webservice.integracion.ihsa.mx/UsuariosWebservice/validarEmailResponse")
    public boolean validarEmail(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
