package mx.ihsa.mybatis.mapper;

import java.util.List;
import mx.ihsa.mybatis.model.Cliente;
import mx.ihsa.mybatis.model.ClienteExample;
import org.apache.ibatis.annotations.Param;

public interface ClienteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cliente
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    long countByExample(ClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cliente
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int deleteByExample(ClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cliente
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int deleteByPrimaryKey(Integer idCte);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cliente
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int insert(Cliente record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cliente
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int insertSelective(Cliente record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cliente
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    List<Cliente> selectByExample(ClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cliente
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    Cliente selectByPrimaryKey(Integer idCte);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cliente
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") Cliente record, @Param("example") ClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cliente
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int updateByExample(@Param("record") Cliente record, @Param("example") ClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cliente
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int updateByPrimaryKeySelective(Cliente record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cliente
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int updateByPrimaryKey(Cliente record);
}