package mx.ihsa.mybatis.mapper;

import java.util.List;
import mx.ihsa.mybatis.model.Cuenta;
import mx.ihsa.mybatis.model.CuentaExample;
import org.apache.ibatis.annotations.Param;

public interface CuentaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cuenta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    long countByExample(CuentaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cuenta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int deleteByExample(CuentaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cuenta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int deleteByPrimaryKey(Integer idCta);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cuenta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int insert(Cuenta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cuenta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int insertSelective(Cuenta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cuenta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    List<Cuenta> selectByExample(CuentaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cuenta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    Cuenta selectByPrimaryKey(Integer idCta);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cuenta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") Cuenta record, @Param("example") CuentaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cuenta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int updateByExample(@Param("record") Cuenta record, @Param("example") CuentaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cuenta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int updateByPrimaryKeySelective(Cuenta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cuenta
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int updateByPrimaryKey(Cuenta record);
}