package mx.ihsa.mybatis.mapper;

import java.util.List;
import mx.ihsa.mybatis.model.Movimiento;
import mx.ihsa.mybatis.model.MovimientoExample;
import org.apache.ibatis.annotations.Param;

public interface MovimientoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    long countByExample(MovimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int deleteByExample(MovimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int deleteByPrimaryKey(Integer idMovCta);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int insert(Movimiento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int insertSelective(Movimiento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    List<Movimiento> selectByExample(MovimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    Movimiento selectByPrimaryKey(Integer idMovCta);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") Movimiento record, @Param("example") MovimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int updateByExample(@Param("record") Movimiento record, @Param("example") MovimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int updateByPrimaryKeySelective(Movimiento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movimiento
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int updateByPrimaryKey(Movimiento record);
}