package mx.ihsa.mybatis.mapper;

import java.util.List;
import mx.ihsa.mybatis.model.Perfil;
import mx.ihsa.mybatis.model.PerfilExample;
import org.apache.ibatis.annotations.Param;

public interface PerfilMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    long countByExample(PerfilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int deleteByExample(PerfilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int deleteByPrimaryKey(Integer idPerfil);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int insert(Perfil record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int insertSelective(Perfil record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    List<Perfil> selectByExample(PerfilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    Perfil selectByPrimaryKey(Integer idPerfil);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") Perfil record, @Param("example") PerfilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int updateByExample(@Param("record") Perfil record, @Param("example") PerfilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int updateByPrimaryKeySelective(Perfil record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.perfil
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int updateByPrimaryKey(Perfil record);
}