package mx.ihsa.mybatis.mapper;

import java.util.List;
import mx.ihsa.mybatis.model.Usuario;
import mx.ihsa.mybatis.model.UsuarioExample;
import org.apache.ibatis.annotations.Param;

public interface UsuarioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    long countByExample(UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int deleteByExample(UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int deleteByPrimaryKey(Integer idUsuario);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int insert(Usuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int insertSelective(Usuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    List<Usuario> selectByExample(UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    Usuario selectByPrimaryKey(Integer idUsuario);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") Usuario record, @Param("example") UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int updateByExample(@Param("record") Usuario record, @Param("example") UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int updateByPrimaryKeySelective(Usuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Fri Feb 22 12:24:36 CST 2019
     */
    int updateByPrimaryKey(Usuario record);
}